// <auto-generated />
using System;
using Core.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Core.Migrations
{
    [DbContext(typeof(GuestSideDb))]
    [Migration("20250112153351_restaurantFix")]
    partial class restaurantFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Core.Entities.Guest.GuestActiveLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GuestID")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuestID")
                        .IsUnique();

                    b.ToTable("GuestLanguages", "CSI");
                });

            modelBuilder.Entity("Core.Core.Entities.Payment.PaymentOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Payment_Method_Name");

                    b.HasKey("Id");

                    b.ToTable("PaymentOptions", "CSI");
                });

            modelBuilder.Entity("Core.Core.Entities.Restaurant.RestaurantItemToCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("RestaunrantItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("RestaurantCartId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RestaunrantItemId");

                    b.HasIndex("RestaurantCartId");

                    b.ToTable("RestaurantItemToCarts", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Advertisements.Advertisements", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AdvertisementTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Pictures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementTypeId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Advertisements", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Advertisments.AdvertisementType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("AdvertisementTypes", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Audio.AudioResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AudioFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoiceType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.ToTable("AudioResponses", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Audio.AudioResponseCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AudioResponseCategories", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Feedbacks.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<long>("TasksId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TasksId");

                    b.ToTable("Feedbacks", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Guest.Guests", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFrequentGuest")
                        .HasColumnType("bit");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preferences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("RoomId");

                    b.HasIndex("StatusId");

                    b.ToTable("Guests", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Guest.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Statuses", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Hotel.GeoLocation.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MapUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("Locations", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Hotel.Hotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LanguagePackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pictures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguagePackId");

                    b.ToTable("Hotels", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GuestId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LanguagePackId")
                        .HasColumnType("bigint");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguagePackId");

                    b.ToTable("Carts", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.ItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LanguagePackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryName");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguagePackId");

                    b.ToTable("ItemCategories", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.Items", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ItemCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LanguagePackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemName");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguagePackId");

                    b.ToTable("Items", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.OrderableItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ItemCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LanguagePackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemName");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguagePackId");

                    b.ToTable("OrderableItems", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Language.LanguagePack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LanguagePacks", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.LogEntities.Logs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("bit");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Notification.GuestNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GuestId")
                        .HasColumnType("bigint");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("NotificationId");

                    b.ToTable("GuestNotifications", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Notification.Notifications", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Notifications", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Notification.StaffNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffNotifications", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Payment.RestaurantOrderPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Time_Of_Payment");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PaymentOptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RestaurantCartId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentOptionId");

                    b.HasIndex("RestaurantCartId")
                        .IsUnique();

                    b.ToTable("RestaurantOrderPayments", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.RestaunrantItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Allergens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvaliable")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RestaurantId")
                        .HasColumnType("bigint");

                    b.Property<long>("RestaurantItemCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("RestaurantItemCategoryId");

                    b.ToTable("RestaunrantItems", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.RestaurantCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GuestId")
                        .HasColumnType("bigint");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("RestaurantCarts", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.RestaurantItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RestaurantItemCategories", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.Restaurants", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaunrantCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Room.QRCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("QrCodeImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("QRCodes", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Room.RoomCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("RoomCategories", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Room.Rooms", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Pictures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoomCategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("WhatWillRobotSay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("RoomCategoryId");

                    b.ToTable("Rooms", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Staff.StaffCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("StaffCategories", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Staff.Staffs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StaffCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StaffCategoryId");

                    b.ToTable("Staffs", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Staff.TaskToStaff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TaskId");

                    b.ToTable("CartToStaffs", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.TaskCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("TaskCategories", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.Tasks", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderableItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OrderableItemId");

                    b.ToTable("Tasks", "CSI");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.TasksStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NameOfStatus");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("TaskStatus", "CSI");
                });

            modelBuilder.Entity("Core.Core.Entities.Guest.GuestActiveLanguage", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Guest.Guests", "Guest")
                        .WithOne("ActiveLanguage")
                        .HasForeignKey("Core.Core.Entities.Guest.GuestActiveLanguage", "GuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Core.Core.Entities.Restaurant.RestaurantItemToCart", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Restaurant.RestaunrantItem", "RestaunrantItem")
                        .WithMany("RestaurantItemToCarts")
                        .HasForeignKey("RestaunrantItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Restaurant.RestaurantCart", "RestaurantCart")
                        .WithMany("RestaurantItemToCarts")
                        .HasForeignKey("RestaurantCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaunrantItem");

                    b.Navigation("RestaurantCart");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Advertisements.Advertisements", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Advertisments.AdvertisementType", "AdvertisementType")
                        .WithMany("Advertisements")
                        .HasForeignKey("AdvertisementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertisementType");

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Advertisments.AdvertisementType", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Audio.AudioResponse", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Audio.AudioResponseCategory", "Categorie")
                        .WithMany("AudioResponses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Feedbacks.Feedback", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Task.Tasks", "Task")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Guest.Guests", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Room.Rooms", "Room")
                        .WithMany("Guests")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Guest.Status", "Status")
                        .WithMany("GuestsStatues")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Status");

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Guest.Status", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Hotel.GeoLocation.Location", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Hotel.Hotel", "Hotel")
                        .WithOne("Location")
                        .HasForeignKey("GuestSide.Core.Entities.Hotel.GeoLocation.Location", "HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Hotel.Hotel", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", null)
                        .WithMany("Hotels")
                        .HasForeignKey("LanguagePackId");

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.Cart", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Guest.Guests", "guest")
                        .WithMany("Tasks")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", null)
                        .WithMany("Carts")
                        .HasForeignKey("LanguagePackId");

                    b.Navigation("guest");

                    b.Navigation("language");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.ItemCategory", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", null)
                        .WithMany("ItemCategories")
                        .HasForeignKey("LanguagePackId");

                    b.Navigation("language");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.Items", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Item.ItemCategory", "ItemCategory")
                        .WithMany("Item")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", null)
                        .WithMany("Items")
                        .HasForeignKey("LanguagePackId");

                    b.Navigation("ItemCategory");

                    b.Navigation("language");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.OrderableItem", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Item.ItemCategory", "ItemCategory")
                        .WithMany()
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", null)
                        .WithMany("OrderableItems")
                        .HasForeignKey("LanguagePackId");

                    b.Navigation("ItemCategory");

                    b.Navigation("language");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Notification.GuestNotification", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Guest.Guests", "Guest")
                        .WithMany("GuestNotifications")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Notification.Notifications", "Notifications")
                        .WithMany("GuestNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Notification.Notifications", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Notification.StaffNotification", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Notification.Notifications", "Notifications")
                        .WithMany("StaffNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Staff.Staffs", "Staff")
                        .WithMany("StaffNotifications")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Payment.RestaurantOrderPayment", b =>
                {
                    b.HasOne("Core.Core.Entities.Payment.PaymentOption", "PaymentOption")
                        .WithMany("RestaurantOrderPayments")
                        .HasForeignKey("PaymentOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Restaurant.RestaurantCart", "RestaurantCart")
                        .WithOne("RestaurantOrderPayment")
                        .HasForeignKey("GuestSide.Core.Entities.Payment.RestaurantOrderPayment", "RestaurantCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentOption");

                    b.Navigation("RestaurantCart");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.RestaunrantItem", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Restaurant.Restaurants", "Restaurants")
                        .WithMany("Items")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Restaurant.RestaurantItemCategory", "restaurantItemCategory")
                        .WithMany("restaunrantItems")
                        .HasForeignKey("RestaurantItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurants");

                    b.Navigation("restaurantItemCategory");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.RestaurantCart", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Guest.Guests", "Guests")
                        .WithMany("RestaurantCart")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guests");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Room.QRCode", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Room.Rooms", "Room")
                        .WithOne("QRCode")
                        .HasForeignKey("GuestSide.Core.Entities.Room.QRCode", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Room.RoomCategory", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Room.Rooms", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Hotel.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Room.RoomCategory", "RoomCategory")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomCategory");

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Staff.StaffCategory", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Staff.Staffs", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Staff.StaffCategory", "StaffCategory")
                        .WithMany("Staff")
                        .HasForeignKey("StaffCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffCategory");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Staff.TaskToStaff", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Staff.Staffs", "Staff")
                        .WithMany("TaskToStaff")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Task.TasksStatus", "Status")
                        .WithMany("taskToStaff")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Task.Tasks", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Status");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.TaskCategory", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.Tasks", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Item.Cart", "Cart")
                        .WithMany("Tasks")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Task.TaskCategory", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestSide.Core.Entities.Item.OrderableItem", "OrderableItem")
                        .WithMany("Tasks")
                        .HasForeignKey("OrderableItemId");

                    b.Navigation("Cart");

                    b.Navigation("Category");

                    b.Navigation("OrderableItem");

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.TasksStatus", b =>
                {
                    b.HasOne("GuestSide.Core.Entities.Language.LanguagePack", "languagePack")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("languagePack");
                });

            modelBuilder.Entity("Core.Core.Entities.Payment.PaymentOption", b =>
                {
                    b.Navigation("RestaurantOrderPayments");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Advertisments.AdvertisementType", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Audio.AudioResponseCategory", b =>
                {
                    b.Navigation("AudioResponses");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Guest.Guests", b =>
                {
                    b.Navigation("ActiveLanguage")
                        .IsRequired();

                    b.Navigation("GuestNotifications");

                    b.Navigation("RestaurantCart");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Guest.Status", b =>
                {
                    b.Navigation("GuestsStatues");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Hotel.Hotel", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.Cart", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.ItemCategory", b =>
                {
                    b.Navigation("Item");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Item.OrderableItem", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Language.LanguagePack", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Hotels");

                    b.Navigation("ItemCategories");

                    b.Navigation("Items");

                    b.Navigation("OrderableItems");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Notification.Notifications", b =>
                {
                    b.Navigation("GuestNotifications");

                    b.Navigation("StaffNotifications");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.RestaunrantItem", b =>
                {
                    b.Navigation("RestaurantItemToCarts");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.RestaurantCart", b =>
                {
                    b.Navigation("RestaurantItemToCarts");

                    b.Navigation("RestaurantOrderPayment");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.RestaurantItemCategory", b =>
                {
                    b.Navigation("restaunrantItems");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Restaurant.Restaurants", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Room.RoomCategory", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Room.Rooms", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("QRCode");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Staff.StaffCategory", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Staff.Staffs", b =>
                {
                    b.Navigation("StaffNotifications");

                    b.Navigation("TaskToStaff");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.TaskCategory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.Tasks", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("GuestSide.Core.Entities.Task.TasksStatus", b =>
                {
                    b.Navigation("taskToStaff");
                });
#pragma warning restore 612, 618
        }
    }
}
