//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Application.ErrorSuccessKeys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Application.ErrorSuccessKeys.ErrorKeys", typeof(ErrorKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to წვდომა უარყოფილია.
        /// </summary>
        internal static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ანგარიში დაბლოკილია.
        /// </summary>
        internal static string ACCOUNT_LOCKED {
            get {
                return ResourceManager.GetString("ACCOUNT_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კავშირის შეცდომა.
        /// </summary>
        internal static string CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მონაცემები არ მოიძებნა.
        /// </summary>
        internal static string DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დუბლირებული ჩანაწერი.
        /// </summary>
        internal static string DUPLICATE_ENTRY {
            get {
                return ResourceManager.GetString("DUPLICATE_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ.ფოსტა უკვე არსებობს.
        /// </summary>
        internal static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის ზომა მეტისმეტად დიდია.
        /// </summary>
        internal static string FILE_TOO_LARGE {
            get {
                return ResourceManager.GetString("FILE_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არასწორი სერტიფიკატები.
        /// </summary>
        internal static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არასწორი ფორმატი.
        /// </summary>
        internal static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არასწორი შეყვანილი მონაცემები.
        /// </summary>
        internal static string INVALID_INPUT {
            get {
                return ResourceManager.GetString("INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არასწორი ტოკენი.
        /// </summary>
        internal static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ოპერაცია ვერ შესრულდა.
        /// </summary>
        internal static string OPERATION_FAILED {
            get {
                return ResourceManager.GetString("OPERATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვერდი არ მოიძებნა.
        /// </summary>
        internal static string PAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლი არასწორია.
        /// </summary>
        internal static string PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნებართვა უარყოფილია.
        /// </summary>
        internal static string PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოთხოვნის დრო ამოიწურა.
        /// </summary>
        internal static string REQUEST_TIMEOUT {
            get {
                return ResourceManager.GetString("REQUEST_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რესურსი მიუწვდომელია.
        /// </summary>
        internal static string RESOURCE_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("RESOURCE_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სერვერის შეცდომა.
        /// </summary>
        internal static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ავტორიზაციის გარეშე მოქმედება.
        /// </summary>
        internal static string UNAUTHORIZED_ACTION {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებელი არ მოიძებნა.
        /// </summary>
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
