//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Application.ErrorSuccessKeys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StandartTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StandartTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Application.ErrorSuccessKeys.StandartTexts", typeof(StandartTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოქმედება წარმატებით დასრულდა.
        /// </summary>
        internal static string ACTION_COMPLETED {
            get {
                return ResourceManager.GetString("ACTION_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მონაცემები წარმატებით შეინახა.
        /// </summary>
        internal static string DATA_SAVED {
            get {
                return ResourceManager.GetString("DATA_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ.ფოსტა წარმატებით გაიგზავნა.
        /// </summary>
        internal static string EMAIL_SENT {
            get {
                return ResourceManager.GetString("EMAIL_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელემენტი წარმატებით დაემატა.
        /// </summary>
        internal static string ITEM_ADDED {
            get {
                return ResourceManager.GetString("ITEM_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ოპერაცია წარმატებით შესრულდა.
        /// </summary>
        internal static string OPERATION_SUCCESSFUL {
            get {
                return ResourceManager.GetString("OPERATION_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროფილი წარმატებით განახლდა.
        /// </summary>
        internal static string PROFILE_UPDATED {
            get {
                return ResourceManager.GetString("PROFILE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რეგისტრაცია წარმატებით დასრულდა&quot;.
        /// </summary>
        internal static string REGISTRATION_SUCCESSFUL {
            get {
                return ResourceManager.GetString("REGISTRATION_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოთხოვნა წარმატებით დამუშავდა.
        /// </summary>
        internal static string REQUEST_PROCESSED {
            get {
                return ResourceManager.GetString("REQUEST_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გამოწერა წარმატებით შესრულდა.
        /// </summary>
        internal static string SUBSCRIPTION_SUCCESSFUL {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მონაცემები წარმატებით განთავსდა საცავში..
        /// </summary>
        internal static string Succes_After_Insert {
            get {
                return ResourceManager.GetString("Succes_After_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მონაცემები წარმატებით განახლდა საცავში..
        /// </summary>
        internal static string Succes_After_Update {
            get {
                return ResourceManager.GetString("Succes_After_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოთხოვნა შესრულდა წარმატებით..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომხმარებელი წარმატებით შეიქმნა.
        /// </summary>
        internal static string USER_CREATED {
            get {
                return ResourceManager.GetString("USER_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ვერიფიკაცია წარმატებით დასრულდა.
        /// </summary>
        internal static string VERIFICATION_SUCCESS {
            get {
                return ResourceManager.GetString("VERIFICATION_SUCCESS", resourceCulture);
            }
        }
    }
}
